[project]
name = "twilight"
version = "0.1.0"
description = "A Himawari Satellite Data Visualization System"
authors = [{ name = "up1and", email = "piratecb@gmail.com" }]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[tool.uv.workspace]
members = ["server", "worker"]

[project.optional-dependencies]
docs = [
    "sphinx>=8.0",
    "shibuya",
]