[project]
name = "server"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "minio>=7.2.15",
    "rasterio==1.4.3",
    "numpy",
    "flask>=3.1.0",
    "flask-caching>=2.3.1",
    "redis>=6.2.0",
    "rio-tiler>=7.6.1",
    "pycoast>=1.7.0",
    "imageio[ffmpeg]>=2.36.0",
    "python-dotenv>=1.2.2",
    "platformdirs>=4.9.4",
]
